[package]
name = "native"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[lib]
name = "native"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
neon-serde = "0.1.1"
serde_derive = "1.0.90"
